### YamlMime:ManagedReference

apiRules:
- exclude:
    hasAttribute:
      uid: GHIElectronics.Endpoint.Core.
      ctorArguments:
        - System.AttributeTargets.Class
      ctorNamedArguments:
        Inherited: "true"


